// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzWtJISj_lsJyJtA2OvjunZ-YCHOZAEXA',
    appId: '1:955055547973:android:13780bc8c3a4475a0f652c',
    messagingSenderId: '955055547973',
    projectId: 'fyp-travel-guide-6b527',
    databaseURL: 'https://fyp-travel-guide-6b527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-travel-guide-6b527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDxxQdRI2zODyBuHkiK7V1CXedelh8K8',
    appId: '1:955055547973:ios:cfa64d075225f13c0f652c',
    messagingSenderId: '955055547973',
    projectId: 'fyp-travel-guide-6b527',
    databaseURL: 'https://fyp-travel-guide-6b527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-travel-guide-6b527.appspot.com',
    iosClientId: '955055547973-6sjp5jj5et6bpp6as0fr5op1rribgulm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypProject',
  );
}
